POST https://strapi-store-server.onrender.com/api/auth/local
Content-Type: application/json

{
  "identifier":"test@test.com","password":"secret"
}

###
POST https://strapi-store-server.onrender.com/api/auth/local/register
Content-Type: application/json

{
  "username":"helia ghafari","email":"helia@gmail.com","password":"secret"
}

###
POST https://strapi-store-server.onrender.com/api/auth/local/register
Content-Type: application/json

{
  "username":"james smith","email":"james@gmail.com","password":"secret"
}

###
POST https://strapi-store-server.onrender.com/api/auth/local/register
Content-Type: application/json

{
  "username":"james2 smith","email":"james2@gmail.com","password":"secret"
}

###
POST https://strapi-store-server.onrender.com/api/auth/local/register
Content-Type: application/json

{
    "username":"james1 smith","email":"james1@gmail.com","password":"secret"
}

###
POST https://strapi-store-server.onrender.com/api/auth/local/register
Content-Type: application/json

{}

###
GET https://strapi-store-server.onrender.com/api/products?page=2
Accept: application/json

###
GET https://strapi-store-server.onrender.com/api/products?price=15000
Accept: application/json

###
GET https://strapi-store-server.onrender.com/api/products?company=luxora
Accept: application/json

###
GET https://strapi-store-server.onrender.com/api/products?search=chair
Accept: application/json

###
GET https://strapi-store-server.onrender.com/api/products/16
Accept: application/json

###
GET http://localhost:80/api/item?id=99
Accept: application/json

###
GET https://strapi-store-server.onrender.com/api/products?featured=true
Accept: application/json

###


